language: cpp

branches:
  only:
  - rodrigo

addons:
  apt:
    update: true
    packages:
    - openmpi-bin
    - libopenmpi-dev
    - libhdf5-openmpi-dev

before_script:
  - sh travis/setup.sh

script:
  - ./config Linux-x86_64-g++ --charm-arch mpi-linux-x86_64
  - cd Linux-x86_64-g++
  - make
  - mpirun -np 4 namd2 ../src/alanin
