---
- hosts: all
  gather_facts: yes
  tasks:
  - name: Create /efs directory
    become: yes
    shell: |
      mkdir /home/ubuntu/efs
      chmod -R 777 /home/ubuntu/efs

  - name: Mount /efs directory
    become: yes
    shell: |
      mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport {{ efs_mount_ip }}:/ efs
      chmod -R 777 /home/ubuntu/efs
