---

- name: Create security group playbook
  hosts: localhost 
  gather_facts: false
  tasks:
  - name: Create security group in ec2 us-east-1
    ec2_group:
      name: namd_mpi_group
      description: Security group for NAMD
      region: us-east-1
      aws_secret_key: "{{lookup('file', '~/.clap/private/secret_access_key.pem') }}"
      aws_access_key: "{{lookup('file', '~/.clap/private/access_key.pub') }}"
      state: present
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: all
          group_name: namd_mpi_group
    register: creation_result
    
  - name: Print creation result dictionary
    debug:
      msg: "group={{ creation_result.group_id }}"
